# Generated by Django 3.2.4 on 2021-06-07 13:03

from django.db import migrations, models
import glyke_back.models


class Migration(migrations.Migration):

    dependencies = [
        ('glyke_back', '0006_auto_20210607_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=models.SET(glyke_back.models.get_deleted_instance_decorated), related_name='products', to='glyke_back.category'),
        ),
    ]
