# Generated by Django 3.2.4 on 2021-06-07 15:07

from django.db import migrations, models
import django.db.models.deletion
import glyke_back.models


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0012_auto_20210607_1807'),
        ('glyke_back', '0007_alter_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='check',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='product',
            name='photos',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='photologue.gallery'),
        ),
        migrations.AlterField(
            model_name='checkline',
            name='line_number',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=models.SET(glyke_back.models.get_deleted_instance_decorated), related_name='products', to='glyke_back.category'),
        ),
    ]
