# Generated by Django 3.2 on 2021-05-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio_back', '0003_auto_20210512_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tile',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
