# Generated by Django 3.2 on 2021-05-17 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folio_back', '0004_auto_20210517_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tile',
            old_name='active',
            new_name='is_active',
        ),
    ]
